/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.adivinanumero.diseno;

import java.awt.Frame;
import javax.swing.JFrame;

/**
 *
 * @author dainer
 */
public class MensajeGameOver extends javax.swing.JDialog {
    
    JFrame frame = new JFrame();
    /**
     * Creates new form MensajeGameOver
     */
    public MensajeGameOver(java.awt.Frame parent, JFrame frm, boolean modal, String msg1, String msg2) {
        super(parent, modal);

        frame = frm;
        
        initComponents();
        
        this.jlbl_mensaje.setText(msg1);
        this.jbtn_reintentar.setText(msg2);
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbl_cerrar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlbl_mensaje = new javax.swing.JLabel();
        jbtn_menu = new javax.swing.JButton();
        jbtn_reintentar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 280));
        setMinimumSize(new java.awt.Dimension(400, 280));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_cerrar.setFont(new java.awt.Font("Harrington", 0, 55)); // NOI18N
        jlbl_cerrar.setForeground(new java.awt.Color(255, 0, 0));
        jlbl_cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_cerrar.setText("•");
        jlbl_cerrar.setToolTipText("");
        jlbl_cerrar.setFocusable(false);
        jlbl_cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlbl_cerrar.setMaximumSize(new java.awt.Dimension(22, 35));
        jlbl_cerrar.setMinimumSize(new java.awt.Dimension(22, 35));
        jlbl_cerrar.setPreferredSize(new java.awt.Dimension(22, 35));
        jlbl_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbl_cerrarMouseClicked(evt);
            }
        });
        jPanel1.add(jlbl_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 30));

        jPanel2.setBackground(new java.awt.Color(69, 69, 69));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_mensaje.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jlbl_mensaje.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_mensaje.setText("Perdiste");
        jPanel2.add(jlbl_mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 40, 320, -1));

        jbtn_menu.setBackground(new java.awt.Color(135, 206, 235));
        jbtn_menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtn_menu.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_menu.setText("Menu");
        jbtn_menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbtn_menu.setContentAreaFilled(false);
        jbtn_menu.setFocusPainted(false);
        jbtn_menu.setFocusable(false);
        jbtn_menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_menu.setPreferredSize(new java.awt.Dimension(100, 100));
        jbtn_menu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/botonLargo.png"))); // NOI18N
        jbtn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_menuActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 140, 60));

        jbtn_reintentar.setBackground(new java.awt.Color(135, 206, 235));
        jbtn_reintentar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtn_reintentar.setForeground(new java.awt.Color(135, 206, 235));
        jbtn_reintentar.setText("Jugar de nuevo");
        jbtn_reintentar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 206, 235)));
        jbtn_reintentar.setContentAreaFilled(false);
        jbtn_reintentar.setFocusPainted(false);
        jbtn_reintentar.setFocusable(false);
        jbtn_reintentar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_reintentar.setPreferredSize(new java.awt.Dimension(100, 100));
        jbtn_reintentar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/botonLargo2.png"))); // NOI18N
        jbtn_reintentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_reintentarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn_reintentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 140, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_reintentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_reintentarActionPerformed
//        frame.dispose();
//        
//        JuegoPrincipal jp = new JuegoPrincipal();
//        jp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtn_reintentarActionPerformed

    private void jbtn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_menuActionPerformed
        frame.dispose();
        
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtn_menuActionPerformed

    private void jlbl_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_cerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jlbl_cerrarMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        FiveCodMover.FiveCodMoverJDialog.MousePressed(evt);
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        FiveCodMover.FiveCodMoverJDialog.MouseDraggedJDialog(evt, this);
    }//GEN-LAST:event_formMouseDragged
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MensajeGameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MensajeGameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MensajeGameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MensajeGameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MensajeGameOver dialog = new MensajeGameOver(new javax.swing.JFrame(), null, true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtn_menu;
    public javax.swing.JButton jbtn_reintentar;
    private javax.swing.JLabel jlbl_cerrar;
    public javax.swing.JLabel jlbl_mensaje;
    // End of variables declaration//GEN-END:variables
}
